export const koreanBibleProgressKey = "xcan:progress:korean_bible_reading";
export const legacyKoreanBibleProgressKey = "xcan:korean-bible-reading-progress:v3";
export const englishBibleProgressKey = "xcan:progress:english_bible_reading";
export const koreanBiblePlaylistId = "PLjj_uvKdTemCV3tBQ3iHCe5O-HPXsjtjn";
export const koreanBiblePlaylistLength = 365;

export type KoreanBibleVideo = {
  day: number;
  playlistIndex: number;
  videoId?: string;
  book: string;
  chapters: string;
  title: string;
};

export type KoreanBibleBookGroup = {
  book: string;
  startDay: number;
  endDay: number;
  items: KoreanBibleVideo[];
};

export type EnglishBibleVideo = {
  book: string;
  videoId: string;
  title: string;
};

export function playlistIndexForBibleDay(day: number) {
  return Math.max(0, koreanBiblePlaylistLength - day);
}

// Generated from the public CGN YouTube playlist on 2026-07-09.
export const koreanBibleVideos: KoreanBibleVideo[] = [
  {
    day: 1,
    playlistIndex: 364,
    videoId: "3-NAx-ECs70",
    book: "창세기",
    chapters: "1~4장",
    title: "창세기 1~4장",
  },
  {
    day: 2,
    playlistIndex: 363,
    videoId: "-a-q4tBYVYs",
    book: "창세기",
    chapters: "5~9장",
    title: "창세기 5~9장",
  },
  {
    day: 3,
    playlistIndex: 362,
    videoId: "ek6UR53q_sU",
    book: "창세기",
    chapters: "10~13장",
    title: "창세기 10~13장",
  },
  {
    day: 4,
    playlistIndex: 361,
    videoId: "jrsrO_F5r-0",
    book: "창세기",
    chapters: "14~17장",
    title: "창세기 14~17장",
  },
  {
    day: 5,
    playlistIndex: 360,
    videoId: "9pLEnCvJRUo",
    book: "창세기",
    chapters: "18~19장",
    title: "창세기 18~19장",
  },
  {
    day: 6,
    playlistIndex: 359,
    videoId: "Ls6E4kTbjGk",
    book: "창세기",
    chapters: "20~22장",
    title: "창세기 20~22장",
  },
  {
    day: 7,
    playlistIndex: 358,
    videoId: "GCMVHC3Roio",
    book: "창세기",
    chapters: "23~24장",
    title: "창세기 23~24장",
  },
  {
    day: 8,
    playlistIndex: 357,
    videoId: "rh_RBkLf8j0",
    book: "창세기",
    chapters: "25~26장",
    title: "창세기 25~26장",
  },
  {
    day: 9,
    playlistIndex: 356,
    videoId: "EtnOiYlSn9Q",
    book: "창세기",
    chapters: "27~28장",
    title: "창세기 27~28장",
  },
  {
    day: 10,
    playlistIndex: 355,
    videoId: "LxVHgPy5GaU",
    book: "창세기",
    chapters: "29~30장",
    title: "창세기 29~30장",
  },
  {
    day: 11,
    playlistIndex: 354,
    videoId: "D8UW4mJvuCw",
    book: "창세기",
    chapters: "31~32장",
    title: "창세기 31~32장",
  },
  {
    day: 12,
    playlistIndex: 353,
    videoId: "sFIx9ussQE0",
    book: "창세기",
    chapters: "33~35장",
    title: "창세기 33~35장",
  },
  {
    day: 13,
    playlistIndex: 352,
    videoId: "f6xlfDcGCx4",
    book: "창세기",
    chapters: "36~37장",
    title: "창세기 36~37장",
  },
  {
    day: 14,
    playlistIndex: 351,
    videoId: "b49l3RyJxbY",
    book: "창세기",
    chapters: "38~40장",
    title: "창세기 38~40장",
  },
  {
    day: 15,
    playlistIndex: 350,
    videoId: "yTUDKrSv64Y",
    book: "창세기",
    chapters: "41~42장",
    title: "창세기 41~42장",
  },
  {
    day: 16,
    playlistIndex: 349,
    videoId: "IdbUz-s1FfM",
    book: "창세기",
    chapters: "43~44장",
    title: "창세기 43~44장",
  },
  {
    day: 17,
    playlistIndex: 348,
    videoId: "kIhWOEiTw8g",
    book: "창세기",
    chapters: "45~47장",
    title: "창세기 45~47장",
  },
  {
    day: 18,
    playlistIndex: 347,
    videoId: "LLbVKCN8giY",
    book: "창세기",
    chapters: "48~50장",
    title: "창세기 48~50장",
  },
  {
    day: 19,
    playlistIndex: 346,
    videoId: "bL48YebYx94",
    book: "출애굽기",
    chapters: "1~3장",
    title: "출애굽기 1~3장",
  },
  {
    day: 20,
    playlistIndex: 345,
    videoId: "InxZKKHoZFY",
    book: "출애굽기",
    chapters: "4~6장",
    title: "출애굽기 4~6장",
  },
  {
    day: 21,
    playlistIndex: 344,
    videoId: "zQi7dwlwNBo",
    book: "출애굽기",
    chapters: "7~9장",
    title: "출애굽기 7~9장",
  },
  {
    day: 22,
    playlistIndex: 343,
    videoId: "4S-bCxsJNcA",
    book: "출애굽기",
    chapters: "10~12장",
    title: "출애굽기 10~12장",
  },
  {
    day: 23,
    playlistIndex: 342,
    videoId: "gjALiY3S0YM",
    book: "출애굽기",
    chapters: "13~15장",
    title: "출애굽기 13~15장",
  },
  {
    day: 24,
    playlistIndex: 341,
    videoId: "n7UW4oZsIKg",
    book: "출애굽기",
    chapters: "16~18장",
    title: "출애굽기 16~18장",
  },
  {
    day: 25,
    playlistIndex: 340,
    videoId: "WDrd5M9h1Qw",
    book: "출애굽기",
    chapters: "19~21장",
    title: "출애굽기 19~21장",
  },
  {
    day: 26,
    playlistIndex: 339,
    videoId: "7pe45cRns5M",
    book: "출애굽기",
    chapters: "22~24장",
    title: "출애굽기 22~24장",
  },
  {
    day: 27,
    playlistIndex: 338,
    videoId: "1N_Ao6MK3NE",
    book: "출애굽기",
    chapters: "25~27장",
    title: "출애굽기 25~27장",
  },
  {
    day: 28,
    playlistIndex: 337,
    videoId: "VYRaLpvNwo4",
    book: "출애굽기",
    chapters: "28~29장",
    title: "출애굽기 28~29장",
  },
  {
    day: 29,
    playlistIndex: 336,
    videoId: "Ao2LApm6jZA",
    book: "출애굽기",
    chapters: "30~32장",
    title: "출애굽기 30~32장",
  },
  {
    day: 30,
    playlistIndex: 335,
    videoId: "p0UhoOFceBw",
    book: "출애굽기",
    chapters: "33~34장",
    title: "출애굽기 33~34장",
  },
  {
    day: 31,
    playlistIndex: 334,
    videoId: "H4o3csN6Xg4",
    book: "출애굽기",
    chapters: "35~37장",
    title: "출애굽기 35~37장",
  },
  {
    day: 32,
    playlistIndex: 333,
    videoId: "-7W5qpJb-HM",
    book: "출애굽기",
    chapters: "38~40장",
    title: "출애굽기 38~40장",
  },
  {
    day: 33,
    playlistIndex: 332,
    videoId: "aXehOoPAmHw",
    book: "레위기",
    chapters: "1~4장",
    title: "레위기 1~4장",
  },
  {
    day: 34,
    playlistIndex: 331,
    videoId: "QQuI0S7tsuw",
    book: "레위기",
    chapters: "5~7장",
    title: "레위기 5~7장",
  },
  {
    day: 35,
    playlistIndex: 330,
    videoId: "gDYISs8Wylc",
    book: "레위기",
    chapters: "8~10장",
    title: "레위기 8~10장",
  },
  {
    day: 36,
    playlistIndex: 329,
    videoId: "t5NbWh_whZM",
    book: "레위기",
    chapters: "11~13장",
    title: "레위기 11~13장",
  },
  {
    day: 37,
    playlistIndex: 328,
    videoId: "N3r2rddsYJU",
    book: "레위기",
    chapters: "14~15장",
    title: "레위기 14~15장",
  },
  {
    day: 38,
    playlistIndex: 327,
    videoId: "BjxQyxcI5tI",
    book: "레위기",
    chapters: "16~18장",
    title: "레위기 16~18장",
  },
  {
    day: 39,
    playlistIndex: 326,
    videoId: "4Tfa0BqZ8k0",
    book: "레위기",
    chapters: "19~21장",
    title: "레위기 19~21장",
  },
  {
    day: 40,
    playlistIndex: 325,
    videoId: "GDehd6RDV_I",
    book: "레위기",
    chapters: "22~23장",
    title: "레위기 22~23장",
  },
  {
    day: 41,
    playlistIndex: 324,
    videoId: "tJKDEfc73to",
    book: "레위기",
    chapters: "24~25장",
    title: "레위기 24~25장",
  },
  {
    day: 42,
    playlistIndex: 323,
    videoId: "eVorbNjFEvQ",
    book: "레위기",
    chapters: "26~27장",
    title: "레위기 26~27장",
  },
  {
    day: 43,
    playlistIndex: 322,
    videoId: "AMZxdRJ3XcQ",
    book: "민수기",
    chapters: "1~3장",
    title: "민수기 1~3장",
  },
  {
    day: 44,
    playlistIndex: 321,
    videoId: "ZYNZj-HbDj0",
    book: "민수기",
    chapters: "4~6장",
    title: "민수기 4~6장",
  },
  {
    day: 45,
    playlistIndex: 320,
    videoId: "w9W9zDiMPiQ",
    book: "민수기",
    chapters: "7장",
    title: "민수기 7장",
  },
  {
    day: 46,
    playlistIndex: 319,
    videoId: "80cKWFwDDGw",
    book: "민수기",
    chapters: "8~10장",
    title: "민수기 8~10장",
  },
  {
    day: 47,
    playlistIndex: 318,
    videoId: "FRUkSt-pEfk",
    book: "민수기",
    chapters: "11~13장",
    title: "민수기 11~13장",
  },
  {
    day: 48,
    playlistIndex: 317,
    videoId: "KkdISwrI7SI",
    book: "민수기",
    chapters: "14~15장",
    title: "민수기 14~15장",
  },
  {
    day: 49,
    playlistIndex: 316,
    videoId: "Irj4iCkH1W8",
    book: "민수기",
    chapters: "16~18장",
    title: "민수기 16~18장",
  },
  {
    day: 50,
    playlistIndex: 315,
    videoId: "HqQQMQCdRXg",
    book: "민수기",
    chapters: "19~21장",
    title: "민수기 19~21장",
  },
  {
    day: 51,
    playlistIndex: 314,
    videoId: "kGjcCTJWi6U",
    book: "민수기",
    chapters: "22~24장",
    title: "민수기 22~24장",
  },
  {
    day: 52,
    playlistIndex: 313,
    videoId: "1EjEbo-3V2Q",
    book: "민수기",
    chapters: "25~27장",
    title: "민수기 25~27장",
  },
  {
    day: 53,
    playlistIndex: 312,
    videoId: "iGwlrU1ZmRs",
    book: "민수기",
    chapters: "28~30장",
    title: "민수기 28~30장",
  },
  {
    day: 54,
    playlistIndex: 311,
    videoId: "pmzjarxVJew",
    book: "민수기",
    chapters: "31~32장",
    title: "민수기 31~32장",
  },
  {
    day: 55,
    playlistIndex: 310,
    videoId: "9UL_58r52ok",
    book: "민수기",
    chapters: "33~36장",
    title: "민수기 33~36장",
  },
  {
    day: 56,
    playlistIndex: 309,
    videoId: "KFZlRZWzPoM",
    book: "신명기",
    chapters: "1~2장",
    title: "신명기 1~2장",
  },
  {
    day: 57,
    playlistIndex: 308,
    videoId: "2EpsGErNbGE",
    book: "신명기",
    chapters: "3~4장",
    title: "신명기 3~4장",
  },
  {
    day: 58,
    playlistIndex: 307,
    videoId: "Xd7BLj2vcHU",
    book: "신명기",
    chapters: "5~7장",
    title: "신명기 5~7장",
  },
  {
    day: 59,
    playlistIndex: 306,
    videoId: "Cq7G_ntD5yo",
    book: "신명기",
    chapters: "8~10장",
    title: "신명기 8~10장",
  },
  {
    day: 60,
    playlistIndex: 305,
    videoId: "Mu5DrdC7Ugc",
    book: "신명기",
    chapters: "11~13장",
    title: "신명기 11~13장",
  },
  {
    day: 61,
    playlistIndex: 304,
    videoId: "WWMg1o9MmR8",
    book: "신명기",
    chapters: "14~16장",
    title: "신명기 14~16장",
  },
  {
    day: 62,
    playlistIndex: 303,
    videoId: "_GtFh3-xfaE",
    book: "신명기",
    chapters: "17~19장",
    title: "신명기 17~19장",
  },
  {
    day: 63,
    playlistIndex: 302,
    videoId: "bPzlGJI0jb0",
    book: "신명기",
    chapters: "20~22장",
    title: "신명기 20~22장",
  },
  {
    day: 64,
    playlistIndex: 301,
    videoId: "uLALAN9hs00",
    book: "신명기",
    chapters: "23~26장",
    title: "신명기 23~26장",
  },
  {
    day: 65,
    playlistIndex: 300,
    videoId: "0w2D0SqANKI",
    book: "신명기",
    chapters: "27~28장",
    title: "신명기 27~28장",
  },
  {
    day: 66,
    playlistIndex: 299,
    videoId: "901J9ubSldA",
    book: "신명기",
    chapters: "29~31장",
    title: "신명기 29~31장",
  },
  {
    day: 67,
    playlistIndex: 298,
    videoId: "0UIG8hMngcA",
    book: "신명기",
    chapters: "32~34장",
    title: "신명기 32~34장",
  },
  {
    day: 68,
    playlistIndex: 297,
    videoId: "QAbTrCL4Nmw",
    book: "여호수아",
    chapters: "1~4장",
    title: "여호수아 1~4장",
  },
  {
    day: 69,
    playlistIndex: 296,
    videoId: "jVEldKCdevY",
    book: "여호수아",
    chapters: "5~7장",
    title: "여호수아 5~7장",
  },
  {
    day: 70,
    playlistIndex: 295,
    videoId: "URiCQdzgoUI",
    book: "여호수아",
    chapters: "8~9장",
    title: "여호수아 8~9장",
  },
  {
    day: 71,
    playlistIndex: 294,
    videoId: "Ls3XE3hDAeg",
    book: "여호수아",
    chapters: "10~11장",
    title: "여호수아 10~11장",
  },
  {
    day: 72,
    playlistIndex: 293,
    videoId: "1OUxJ4uQX_M",
    book: "여호수아",
    chapters: "12~14장",
    title: "여호수아 12~14장",
  },
  {
    day: 73,
    playlistIndex: 292,
    videoId: "rn8fQCZ-CeI",
    book: "여호수아",
    chapters: "15~18장",
    title: "여호수아 15~18장",
  },
  {
    day: 74,
    playlistIndex: 291,
    videoId: "QICPBvY73RU",
    book: "여호수아",
    chapters: "19~21장",
    title: "여호수아 19~21장",
  },
  {
    day: 75,
    playlistIndex: 290,
    videoId: "6T60qKTBjxw",
    book: "여호수아",
    chapters: "22~24장",
    title: "여호수아 22~24장",
  },
  {
    day: 76,
    playlistIndex: 289,
    videoId: "9npcUJMtRlE",
    book: "사사기",
    chapters: "1~2장",
    title: "사사기 1~2장",
  },
  {
    day: 77,
    playlistIndex: 288,
    videoId: "3-4uo7VU75E",
    book: "사사기",
    chapters: "3~5장",
    title: "사사기 3~5장",
  },
  {
    day: 78,
    playlistIndex: 287,
    videoId: "Istuu-NzkBI",
    book: "사사기",
    chapters: "6~7장",
    title: "사사기 6~7장",
  },
  {
    day: 79,
    playlistIndex: 286,
    videoId: "rCd-DUzm3Sw",
    book: "사사기",
    chapters: "8~9장",
    title: "사사기 8~9장",
  },
  {
    day: 80,
    playlistIndex: 285,
    videoId: "s7j4KVWYV8A",
    book: "사사기",
    chapters: "10~11장",
    title: "사사기 10~11장",
  },
  {
    day: 81,
    playlistIndex: 284,
    videoId: "O3YtbMHjW2s",
    book: "사사기",
    chapters: "12~14장",
    title: "사사기 12~14장",
  },
  {
    day: 82,
    playlistIndex: 283,
    videoId: "uHWg_I1QvXE",
    book: "사사기",
    chapters: "15~16장",
    title: "사사기 15~16장",
  },
  {
    day: 83,
    playlistIndex: 282,
    videoId: "fORpRw2C1b4",
    book: "사사기",
    chapters: "17~19장",
    title: "사사기 17~19장",
  },
  {
    day: 84,
    playlistIndex: 281,
    videoId: "OhDl6qoexgM",
    book: "사사기",
    chapters: "20~21장",
    title: "사사기 20~21장",
  },
  {
    day: 85,
    playlistIndex: 280,
    videoId: "gT2hWzush2w",
    book: "룻기",
    chapters: "1~4장",
    title: "룻기 1~4장",
  },
  {
    day: 86,
    playlistIndex: 279,
    videoId: "Qy6j3uPrgYM",
    book: "사무엘상",
    chapters: "1~3장",
    title: "사무엘상 1~3장",
  },
  {
    day: 87,
    playlistIndex: 278,
    videoId: "XbvEkVes9qI",
    book: "사무엘상",
    chapters: "4~7장",
    title: "사무엘상 4~7장",
  },
  {
    day: 88,
    playlistIndex: 277,
    videoId: "d-gzkfbVUio",
    book: "사무엘상",
    chapters: "8~10장",
    title: "사무엘상 8~10장",
  },
  {
    day: 89,
    playlistIndex: 276,
    videoId: "X_Euo_ogO9g",
    book: "사무엘상",
    chapters: "11~13장",
    title: "사무엘상 11~13장",
  },
  {
    day: 90,
    playlistIndex: 275,
    videoId: "LkQrwhTXU6Y",
    book: "사무엘상",
    chapters: "14–15장",
    title: "사무엘상 14–15장",
  },
  {
    day: 91,
    playlistIndex: 274,
    videoId: "RoCzBNQNutk",
    book: "사무엘상",
    chapters: "16~17장",
    title: "사무엘상 16~17장",
  },
  {
    day: 92,
    playlistIndex: 273,
    videoId: "ouNbD8BG6wE",
    book: "사무엘상",
    chapters: "18~20장",
    title: "사무엘상 18~20장",
  },
  {
    day: 93,
    playlistIndex: 272,
    videoId: "HKw78bQwwzU",
    book: "사무엘상",
    chapters: "21~23장",
    title: "사무엘상 21~23장",
  },
  {
    day: 94,
    playlistIndex: 271,
    videoId: "vXD_wzB_y1o",
    book: "사무엘상",
    chapters: "24~25장",
    title: "사무엘상 24~25장",
  },
  {
    day: 95,
    playlistIndex: 270,
    videoId: "TUZg7QQwPh4",
    book: "사무엘상",
    chapters: "26~28장",
    title: "사무엘상 26~28장",
  },
  {
    day: 96,
    playlistIndex: 269,
    videoId: "xmJ36eWu_Mk",
    book: "사무엘상",
    chapters: "29~31장",
    title: "사무엘상 29~31장",
  },
  {
    day: 97,
    playlistIndex: 268,
    videoId: "T7QmOzNpHeg",
    book: "사무엘하",
    chapters: "1~2장",
    title: "사무엘하 1~2장",
  },
  {
    day: 98,
    playlistIndex: 267,
    videoId: "fwSQbGpXZZI",
    book: "사무엘하",
    chapters: "3~4장",
    title: "사무엘하 3~4장",
  },
  {
    day: 99,
    playlistIndex: 266,
    videoId: "ylIC8kFh8jQ",
    book: "사무엘하",
    chapters: "5~7장",
    title: "사무엘하 5~7장",
  },
  {
    day: 100,
    playlistIndex: 265,
    videoId: "VPLuw_8e3x0",
    book: "사무엘하",
    chapters: "8~11장",
    title: "사무엘하 8~11장",
  },
  {
    day: 101,
    playlistIndex: 264,
    videoId: "FoWUyKbD_RU",
    book: "사무엘하",
    chapters: "12~13장",
    title: "사무엘하 12~13장",
  },
  {
    day: 102,
    playlistIndex: 263,
    videoId: "sV_lXc2M1t4",
    book: "사무엘하",
    chapters: "14~15장",
    title: "사무엘하 14~15장",
  },
  {
    day: 103,
    playlistIndex: 262,
    videoId: "4DSvnUiDNHY",
    book: "사무엘하",
    chapters: "16~17장",
    title: "사무엘하 16~17장",
  },
  {
    day: 104,
    playlistIndex: 261,
    videoId: "qXr_JkSkF44",
    book: "사무엘하",
    chapters: "18~19장",
    title: "사무엘하 18~19장",
  },
  {
    day: 105,
    playlistIndex: 260,
    videoId: "VCRXGHX-tlw",
    book: "사무엘하",
    chapters: "20~22장",
    title: "사무엘하 20~22장",
  },
  {
    day: 106,
    playlistIndex: 259,
    videoId: "wgc7_o3QyHY",
    book: "사무엘하",
    chapters: "23~24장",
    title: "사무엘하 23~24장",
  },
  {
    day: 107,
    playlistIndex: 258,
    videoId: "r9DGrecRT44",
    book: "열왕기상",
    chapters: "1~2장",
    title: "열왕기상 1~2장",
  },
  {
    day: 108,
    playlistIndex: 257,
    videoId: "-rnsakxmaTs",
    book: "열왕기상",
    chapters: "3~5장",
    title: "열왕기상 3~5장",
  },
  {
    day: 109,
    playlistIndex: 256,
    videoId: "qBLJ7pKnpSo",
    book: "열왕기상",
    chapters: "6~7장",
    title: "열왕기상 6~7장",
  },
  {
    day: 110,
    playlistIndex: 255,
    videoId: "zLheD_IcN8I",
    book: "열왕기상",
    chapters: "8~9장",
    title: "열왕기상 8~9장",
  },
  {
    day: 111,
    playlistIndex: 254,
    videoId: "9-5KeFMo6VU",
    book: "열왕기상",
    chapters: "10~11장",
    title: "열왕기상 10~11장",
  },
  {
    day: 112,
    playlistIndex: 253,
    videoId: "gIm0lGrOLY8",
    book: "열왕기상",
    chapters: "12~13장",
    title: "열왕기상 12~13장",
  },
  {
    day: 113,
    playlistIndex: 252,
    videoId: "kX8djy0_sQc",
    book: "열왕기상",
    chapters: "14~16장",
    title: "열왕기상 14~16장",
  },
  {
    day: 114,
    playlistIndex: 251,
    videoId: "35kfHgyiPuY",
    book: "열왕기상",
    chapters: "17~18장",
    title: "열왕기상 17~18장",
  },
  {
    day: 115,
    playlistIndex: 250,
    videoId: "2EL5OIfUV6A",
    book: "열왕기상",
    chapters: "19~20장",
    title: "열왕기상 19~20장",
  },
  {
    day: 116,
    playlistIndex: 249,
    videoId: "aDDOqOEGDo4",
    book: "열왕기상",
    chapters: "21~22장",
    title: "열왕기상 21~22장",
  },
  {
    day: 117,
    playlistIndex: 248,
    videoId: "VphJPpJ1q8M",
    book: "열왕기하",
    chapters: "1~3장",
    title: "열왕기하 1~3장",
  },
  {
    day: 118,
    playlistIndex: 247,
    videoId: "9iOg5saIipE",
    book: "열왕기하",
    chapters: "4~5장",
    title: "열왕기하 4~5장",
  },
  {
    day: 119,
    playlistIndex: 246,
    videoId: "r36HRrSua0s",
    book: "열왕기하",
    chapters: "6~7장",
    title: "열왕기하 6~7장",
  },
  {
    day: 120,
    playlistIndex: 245,
    videoId: "6nfhMCsBSds",
    book: "열왕기하",
    chapters: "8~9장",
    title: "열왕기하 8~9장",
  },
  {
    day: 121,
    playlistIndex: 244,
    videoId: "uMVDMhHQwfE",
    book: "열왕기하",
    chapters: "10~11장",
    title: "열왕기하 10~11장",
  },
  {
    day: 122,
    playlistIndex: 243,
    videoId: "2lDF0bQLS28",
    book: "열왕기하",
    chapters: "12~14장",
    title: "열왕기하 12~14장",
  },
  {
    day: 123,
    playlistIndex: 242,
    videoId: "kN2k7uO_SI4",
    book: "열왕기하",
    chapters: "15~17장",
    title: "열왕기하 15~17장",
  },
  {
    day: 124,
    playlistIndex: 241,
    videoId: "qqYYHRKxpvY",
    book: "열왕기하",
    chapters: "18~19장",
    title: "열왕기하 18~19장",
  },
  {
    day: 125,
    playlistIndex: 240,
    videoId: "k8k8FHpCnjg",
    book: "열왕기하",
    chapters: "20~22장",
    title: "열왕기하 20~22장",
  },
  {
    day: 126,
    playlistIndex: 239,
    videoId: "bu5KlHa7B2I",
    book: "열왕기하",
    chapters: "23~25장",
    title: "열왕기하 23~25장",
  },
  {
    day: 127,
    playlistIndex: 238,
    videoId: "pi-nyFOzrxQ",
    book: "역대상",
    chapters: "1~2장",
    title: "역대상 1~2장",
  },
  {
    day: 128,
    playlistIndex: 237,
    videoId: "PEMTV3XJtVU",
    book: "역대상",
    chapters: "3~5장",
    title: "역대상 3~5장",
  },
  {
    day: 129,
    playlistIndex: 236,
    videoId: "0_Y8RCq9FCw",
    book: "역대상",
    chapters: "6~7장",
    title: "역대상 6~7장",
  },
  {
    day: 130,
    playlistIndex: 235,
    videoId: "MJMer89YGb4",
    book: "역대상",
    chapters: "8~10장",
    title: "역대상 8~10장",
  },
  {
    day: 131,
    playlistIndex: 234,
    videoId: "PUS2iXH2DjM",
    book: "역대상",
    chapters: "11~12장",
    title: "역대상 11~12장",
  },
  {
    day: 132,
    playlistIndex: 233,
    videoId: "fYX6lmJxlc0",
    book: "역대상",
    chapters: "13~16장",
    title: "역대상 13~16장",
  },
  {
    day: 133,
    playlistIndex: 232,
    videoId: "wWT7mVvWjKY",
    book: "역대상",
    chapters: "17~20장",
    title: "역대상 17~20장",
  },
  {
    day: 134,
    playlistIndex: 231,
    videoId: "ESlI9YWZWMM",
    book: "역대상",
    chapters: "21~23장",
    title: "역대상 21~23장",
  },
  {
    day: 135,
    playlistIndex: 230,
    videoId: "FOfAJDXpbw8",
    book: "역대상",
    chapters: "24~26장",
    title: "역대상 24~26장",
  },
  {
    day: 136,
    playlistIndex: 229,
    videoId: "vaMUDUeKTLI",
    book: "역대상",
    chapters: "27~29장",
    title: "역대상 27~29장",
  },
  {
    day: 137,
    playlistIndex: 228,
    videoId: "GZw_SFQ0-GA",
    book: "역대하",
    chapters: "1~4장",
    title: "역대하 1~4장",
  },
  {
    day: 138,
    playlistIndex: 227,
    videoId: "F_R8Jx7zksI",
    book: "역대하",
    chapters: "5~7장",
    title: "역대하 5~7장",
  },
  {
    day: 139,
    playlistIndex: 226,
    videoId: "SBD57QG7NfE",
    book: "역대하",
    chapters: "8~11장",
    title: "역대하 8~11장",
  },
  {
    day: 140,
    playlistIndex: 225,
    videoId: "PUQ2A1YeUt0",
    book: "역대하",
    chapters: "12~15장",
    title: "역대하 12~15장",
  },
  {
    day: 141,
    playlistIndex: 224,
    videoId: "IQOTa8P_twc",
    book: "역대하",
    chapters: "16~19장",
    title: "역대하 16~19장",
  },
  {
    day: 142,
    playlistIndex: 223,
    videoId: "coSDtOIfNGs",
    book: "역대하",
    chapters: "20~22장",
    title: "역대하 20~22장",
  },
  {
    day: 143,
    playlistIndex: 222,
    videoId: "XkrMcBBKUnI",
    book: "역대하",
    chapters: "23~25장",
    title: "역대하 23~25장",
  },
  {
    day: 144,
    playlistIndex: 221,
    videoId: "Jd9_GZGNVcE",
    book: "역대하",
    chapters: "26~28장",
    title: "역대하 26~28장",
  },
  {
    day: 145,
    playlistIndex: 220,
    videoId: "OzkVVv3NGJ8",
    book: "역대하",
    chapters: "29~31장",
    title: "역대하 29~31장",
  },
  {
    day: 146,
    playlistIndex: 219,
    videoId: "JE_vCYrIct4",
    book: "역대하",
    chapters: "32~33장",
    title: "역대하 32~33장",
  },
  {
    day: 147,
    playlistIndex: 218,
    videoId: "2QW3xw3KXyA",
    book: "역대하",
    chapters: "34~36장",
    title: "역대하 34~36장",
  },
  {
    day: 148,
    playlistIndex: 217,
    videoId: "L0L0PtY-b2s",
    book: "에스라",
    chapters: "1~3장",
    title: "에스라 1~3장",
  },
  {
    day: 149,
    playlistIndex: 216,
    videoId: "PVUl7K00zvw",
    book: "에스라",
    chapters: "4~6장",
    title: "에스라 4~6장",
  },
  {
    day: 150,
    playlistIndex: 215,
    videoId: "D6V4gkF4Gkw",
    book: "에스라",
    chapters: "7~8장",
    title: "에스라 7~8장",
  },
  {
    day: 151,
    playlistIndex: 214,
    videoId: "5Ao9MoTHmhM",
    book: "에스라",
    chapters: "9~10장",
    title: "에스라 9~10장",
  },
  {
    day: 152,
    playlistIndex: 213,
    videoId: "dsvryX8GLBY",
    book: "느헤미야",
    chapters: "1~3장",
    title: "느헤미야 1~3장",
  },
  {
    day: 153,
    playlistIndex: 212,
    videoId: "LQjOYfqNvio",
    book: "느헤미야",
    chapters: "4~6장",
    title: "느헤미야 4~6장",
  },
  {
    day: 154,
    playlistIndex: 211,
    videoId: "mHaOE1_eM6U",
    book: "느헤미야",
    chapters: "7~8장",
    title: "느헤미야 7~8장",
  },
  {
    day: 155,
    playlistIndex: 210,
    videoId: "9wGJVsssO-4",
    book: "느헤미야",
    chapters: "9~10장",
    title: "느헤미야 9~10장",
  },
  {
    day: 156,
    playlistIndex: 209,
    videoId: "boOODG8hYOM",
    book: "느헤미야",
    chapters: "11~13장",
    title: "느헤미야 11~13장",
  },
  {
    day: 157,
    playlistIndex: 208,
    videoId: "-G0J2q60Fnc",
    book: "에스더",
    chapters: "1~3장",
    title: "에스더 1~3장",
  },
  {
    day: 158,
    playlistIndex: 207,
    videoId: "R0j2QL2mVEI",
    book: "에스더",
    chapters: "4~7장",
    title: "에스더 4~7장",
  },
  {
    day: 159,
    playlistIndex: 206,
    videoId: "NSfQTXI6oJs",
    book: "에스더",
    chapters: "8~10장",
    title: "에스더 8~10장",
  },
  {
    day: 160,
    playlistIndex: 205,
    videoId: "Zo_puZZKmNM",
    book: "욥기",
    chapters: "1~4장",
    title: "욥기 1~4장",
  },
  {
    day: 161,
    playlistIndex: 204,
    videoId: "xJGPI1AxFgo",
    book: "욥기",
    chapters: "5~8장",
    title: "욥기 5~8장",
  },
  {
    day: 162,
    playlistIndex: 203,
    videoId: "tOCPP5E4AwM",
    book: "욥기",
    chapters: "9~12장",
    title: "욥기 9~12장",
  },
  {
    day: 163,
    playlistIndex: 202,
    videoId: "lPib1lyFPbY",
    book: "욥기",
    chapters: "13~16장",
    title: "욥기 13~16장",
  },
  {
    day: 164,
    playlistIndex: 201,
    videoId: "BvxlCZv0zDU",
    book: "욥기",
    chapters: "17~21장",
    title: "욥기 17~21장",
  },
  {
    day: 165,
    playlistIndex: 200,
    videoId: "sAYqyLyb7NE",
    book: "욥기",
    chapters: "22~27장",
    title: "욥기 22~27장",
  },
  {
    day: 166,
    playlistIndex: 199,
    videoId: "-totrlmwucA",
    book: "욥기",
    chapters: "28~31장",
    title: "욥기 28~31장",
  },
  {
    day: 167,
    playlistIndex: 198,
    videoId: "BkPkEH-1tqY",
    book: "욥기",
    chapters: "32~35장",
    title: "욥기 32~35장",
  },
  {
    day: 168,
    playlistIndex: 197,
    videoId: "vLZlHfaQsXg",
    book: "욥기",
    chapters: "36~38장",
    title: "욥기 36~38장",
  },
  {
    day: 169,
    playlistIndex: 196,
    videoId: "QATKSVXRJkw",
    book: "욥기",
    chapters: "39~42장",
    title: "욥기 39~42장",
  },
  {
    day: 170,
    playlistIndex: 195,
    videoId: "CPM6W7Mvdnw",
    book: "시편",
    chapters: "1~9편",
    title: "시편 1~9편",
  },
  {
    day: 171,
    playlistIndex: 194,
    videoId: "jqynsFl-Z6g",
    book: "시편",
    chapters: "10~14편",
    title: "시편 10~14편",
  },
  {
    day: 172,
    playlistIndex: 193,
    videoId: "f-SRqZRxfUI",
    book: "시편",
    chapters: "15~19편",
    title: "시편 15~19편",
  },
  {
    day: 173,
    playlistIndex: 192,
    videoId: "djHPo2jx4so",
    book: "시편",
    chapters: "20~26편",
    title: "시편 20~26편",
  },
  {
    day: 174,
    playlistIndex: 191,
    videoId: "PWwvz5-H6S4",
    book: "시편",
    chapters: "27~32편",
    title: "시편 27~32편",
  },
  {
    day: 175,
    playlistIndex: 190,
    videoId: "ibP1HylxsxY",
    book: "시편",
    chapters: "33~37편",
    title: "시편 33~37편",
  },
  {
    day: 176,
    playlistIndex: 189,
    videoId: "OUmIJ9YQuJg",
    book: "시편",
    chapters: "38~43편",
    title: "시편 38~43편",
  },
  {
    day: 177,
    playlistIndex: 188,
    videoId: "l7VybOnVLSg",
    book: "시편",
    chapters: "44~49편",
    title: "시편 44~49편",
  },
  {
    day: 178,
    playlistIndex: 187,
    videoId: "gKmwHTVc_G8",
    book: "시편",
    chapters: "50~55편",
    title: "시편 50~55편",
  },
  {
    day: 179,
    playlistIndex: 186,
    videoId: "qkm6nPzgOPw",
    book: "시편",
    chapters: "56~62편",
    title: "시편 56~62편",
  },
  {
    day: 180,
    playlistIndex: 185,
    videoId: "CHheXpSmONE",
    book: "시편",
    chapters: "63~68편",
    title: "시편 63~68편",
  },
  {
    day: 181,
    playlistIndex: 184,
    videoId: "Brfly-6Svj8",
    book: "시편",
    chapters: "69~72편",
    title: "시편 69~72편",
  },
  {
    day: 182,
    playlistIndex: 183,
    videoId: "oA6a1oSOxCE",
    book: "시편",
    chapters: "73~77편",
    title: "시편 73~77편",
  },
  {
    day: 183,
    playlistIndex: 182,
    videoId: "02l85NQaEWs",
    book: "시편",
    chapters: "78~80편",
    title: "시편 78~80편",
  },
  {
    day: 184,
    playlistIndex: 181,
    videoId: "_tjQRyK2yt0",
    book: "시편",
    chapters: "81~87편",
    title: "시편 81~87편",
  },
  {
    day: 185,
    playlistIndex: 180,
    videoId: "afDprT0Qr0U",
    book: "시편",
    chapters: "88~91편",
    title: "시편 88~91편",
  },
  {
    day: 186,
    playlistIndex: 179,
    videoId: "Ey7zcDhNZlc",
    book: "시편",
    chapters: "92~99편",
    title: "시편 92~99편",
  },
  {
    day: 187,
    playlistIndex: 178,
    videoId: "3nWwgsOegnc",
    book: "시편",
    chapters: "100~104편",
    title: "시편 100~104편",
  },
  {
    day: 188,
    playlistIndex: 177,
    videoId: "IoT4nANzlcM",
    book: "시편",
    chapters: "105~106편",
    title: "시편 105~106편",
  },
  {
    day: 189,
    playlistIndex: 176,
    videoId: "ZR3pUU3Q0M0",
    book: "시편",
    chapters: "107~110편",
    title: "시편 107~110편",
  },
  {
    day: 190,
    playlistIndex: 175,
    videoId: "pWHbERxbQBk",
    book: "시편",
    chapters: "111~118편",
    title: "시편 111~118편",
  },
  {
    day: 191,
    playlistIndex: 174,
    videoId: "nFUbcSq1rmM",
    book: "시편",
    chapters: "119편",
    title: "시편 119편",
  },
  {
    day: 192,
    playlistIndex: 173,
    videoId: "B3Qa0vZx0LA",
    book: "시편",
    chapters: "120~134편",
    title: "시편 120~134편",
  },
  {
    day: 193,
    playlistIndex: 172,
    videoId: "fS2R47xx7To",
    book: "시편",
    chapters: "135~142편",
    title: "시편 135~142편",
  },
  {
    day: 194,
    playlistIndex: 171,
    videoId: "sJuopMGD6CY",
    book: "시편",
    chapters: "143~150편",
    title: "시편 143~150편",
  },
  {
    day: 195,
    playlistIndex: 170,
    videoId: "yLotg211cVc",
    book: "잠언",
    chapters: "1~4장",
    title: "잠언 1~4장",
  },
  {
    day: 196,
    playlistIndex: 169,
    videoId: "M7vGULr-XNg",
    book: "잠언",
    chapters: "5~8장",
    title: "잠언 5~8장",
  },
  {
    day: 197,
    playlistIndex: 168,
    videoId: "EiYaovH8hWs",
    book: "잠언",
    chapters: "9~12장",
    title: "잠언 9~12장",
  },
  {
    day: 198,
    playlistIndex: 167,
    videoId: "78bhLQ2GpOk",
    book: "잠언",
    chapters: "13~15장",
    title: "잠언 13~15장",
  },
  {
    day: 199,
    playlistIndex: 166,
    videoId: "C0N6EkgWoRI",
    book: "잠언",
    chapters: "16~18장",
    title: "잠언 16~18장",
  },
  {
    day: 200,
    playlistIndex: 165,
    videoId: "dpj1195HRZg",
    book: "잠언",
    chapters: "19~21장",
    title: "잠언 19~21장",
  },
  {
    day: 201,
    playlistIndex: 164,
    videoId: "-saciT074vo",
    book: "잠언",
    chapters: "22~24장",
    title: "잠언 22~24장",
  },
  {
    day: 202,
    playlistIndex: 163,
    videoId: "rd7w3SDryok",
    book: "잠언",
    chapters: "25~28장",
    title: "잠언 25~28장",
  },
  {
    day: 203,
    playlistIndex: 162,
    videoId: "AQoTOab7zmA",
    book: "잠언",
    chapters: "29~31장",
    title: "잠언 29~31장",
  },
  {
    day: 204,
    playlistIndex: 161,
    videoId: "rW1oPYlloBI",
    book: "전도서",
    chapters: "1~3장",
    title: "전도서 1~3장",
  },
  {
    day: 205,
    playlistIndex: 160,
    videoId: "ZQ7NY8YYmGQ",
    book: "전도서",
    chapters: "4~7장",
    title: "전도서 4~7장",
  },
  {
    day: 206,
    playlistIndex: 159,
    videoId: "83T1EELboYg",
    book: "전도서",
    chapters: "8~12장",
    title: "전도서 8~12장",
  },
  {
    day: 207,
    playlistIndex: 158,
    videoId: "nOTn0lWV0fk",
    book: "아가",
    chapters: "1~8장",
    title: "아가 1~8장",
  },
  {
    day: 208,
    playlistIndex: 157,
    videoId: "U1el9XkM_AM",
    book: "이사야",
    chapters: "1~4장",
    title: "이사야 1~4장",
  },
  {
    day: 209,
    playlistIndex: 156,
    videoId: "ZN1qQS9555k",
    book: "이사야",
    chapters: "5~7장",
    title: "이사야 5~7장",
  },
  {
    day: 210,
    playlistIndex: 155,
    videoId: "GIZ8fA3jgIU",
    book: "이사야",
    chapters: "8~10장",
    title: "이사야 8~10장",
  },
  {
    day: 211,
    playlistIndex: 154,
    videoId: "1ZxcFO3lNq4",
    book: "이사야",
    chapters: "11~14장",
    title: "이사야 11~14장",
  },
  {
    day: 212,
    playlistIndex: 153,
    videoId: "-UD_QWd9yrA",
    book: "이사야",
    chapters: "15~19장",
    title: "이사야 15~19장",
  },
  {
    day: 213,
    playlistIndex: 152,
    videoId: "rEqaBGLewKU",
    book: "이사야",
    chapters: "20~24장",
    title: "이사야 20~24장",
  },
  {
    day: 214,
    playlistIndex: 151,
    videoId: "XCAwQMbTrqg",
    book: "이사야",
    chapters: "25~28장",
    title: "이사야 25~28장",
  },
  {
    day: 215,
    playlistIndex: 150,
    videoId: "ZKshm3xDm3A",
    book: "이사야",
    chapters: "29~31장",
    title: "이사야 29~31장",
  },
  {
    day: 216,
    playlistIndex: 149,
    videoId: "_SynCTJGQLU",
    book: "이사야",
    chapters: "32~35장",
    title: "이사야 32~35장",
  },
  {
    day: 217,
    playlistIndex: 148,
    videoId: "dApKkb5s-dw",
    book: "이사야",
    chapters: "36~38장",
    title: "이사야 36~38장",
  },
  {
    day: 218,
    playlistIndex: 147,
    videoId: "AbxPQR6Igdk",
    book: "이사야",
    chapters: "39~41장",
    title: "이사야 39~41장",
  },
  {
    day: 219,
    playlistIndex: 146,
    videoId: "uaXSx9F3XWM",
    book: "이사야",
    chapters: "42~44장",
    title: "이사야 42~44장",
  },
  {
    day: 220,
    playlistIndex: 145,
    videoId: "V5xp5ZnhXGM",
    book: "이사야",
    chapters: "45~48장",
    title: "이사야 45~48장",
  },
  {
    day: 221,
    playlistIndex: 144,
    videoId: "8k3n1OxfS0E",
    book: "이사야",
    chapters: "49~51장",
    title: "이사야 49~51장",
  },
  {
    day: 222,
    playlistIndex: 143,
    videoId: "k42PxlqpyUU",
    book: "이사야",
    chapters: "52~55장",
    title: "이사야 52~55장",
  },
  {
    day: 223,
    playlistIndex: 142,
    videoId: "3HnSk_6KZbw",
    book: "이사야",
    chapters: "56~59장",
    title: "이사야 56~59장",
  },
  {
    day: 224,
    playlistIndex: 141,
    videoId: "6-eojQeV_34",
    book: "이사야",
    chapters: "60~63장",
    title: "이사야 60~63장",
  },
  {
    day: 225,
    playlistIndex: 140,
    videoId: "o-GaaJx_zho",
    book: "이사야",
    chapters: "64~66장",
    title: "이사야 64~66장",
  },
  {
    day: 226,
    playlistIndex: 139,
    videoId: "lCvEBBSOGDM",
    book: "예레미야",
    chapters: "1~2장",
    title: "예레미야 1~2장",
  },
  {
    day: 227,
    playlistIndex: 138,
    videoId: "UXVHjunSM-k",
    book: "예레미야",
    chapters: "3~4장",
    title: "예레미야 3~4장",
  },
  {
    day: 228,
    playlistIndex: 137,
    videoId: "eam_ubClut0",
    book: "예레미야",
    chapters: "5~6장",
    title: "예레미야 5~6장",
  },
  {
    day: 229,
    playlistIndex: 136,
    videoId: "NDJzar__qJE",
    book: "예레미야",
    chapters: "7~8장",
    title: "예레미야 7~8장",
  },
  {
    day: 230,
    playlistIndex: 135,
    videoId: "D8m4_zhrv3M",
    book: "예레미야",
    chapters: "9~11장",
    title: "예레미야 9~11장",
  },
  {
    day: 231,
    playlistIndex: 134,
    videoId: "MK5xHMZQ3wY",
    book: "예레미야",
    chapters: "12~14장",
    title: "예레미야 12~14장",
  },
  {
    day: 232,
    playlistIndex: 133,
    videoId: "bxnYxkkEtUc",
    book: "예레미야",
    chapters: "15~17장",
    title: "예레미야 15~17장",
  },
  {
    day: 233,
    playlistIndex: 132,
    videoId: "kHmVfesZ8Ws",
    book: "예레미야",
    chapters: "18~21장",
    title: "예레미야 18~21장",
  },
  {
    day: 234,
    playlistIndex: 131,
    videoId: "BNbUd9C97Xk",
    book: "예레미야",
    chapters: "22~23장",
    title: "예레미야 22~23장",
  },
  {
    day: 235,
    playlistIndex: 130,
    videoId: "SJzzaWieKS4",
    book: "예레미야",
    chapters: "24~26장",
    title: "예레미야 24~26장",
  },
  {
    day: 236,
    playlistIndex: 129,
    videoId: "bKA9mjqNGOw",
    book: "예레미야",
    chapters: "27~29장",
    title: "예레미야 27~29장",
  },
  {
    day: 237,
    playlistIndex: 128,
    videoId: "40PKxJBujR0",
    book: "예레미야",
    chapters: "30~31장",
    title: "예레미야 30~31장",
  },
  {
    day: 238,
    playlistIndex: 127,
    videoId: "nZO8z-9Jtu0",
    book: "예레미야",
    chapters: "32~34장",
    title: "예레미야 32~34장",
  },
  {
    day: 239,
    playlistIndex: 126,
    videoId: "CLC5zB_Ztso",
    book: "예레미야",
    chapters: "35~37장",
    title: "예레미야 35~37장",
  },
  {
    day: 240,
    playlistIndex: 125,
    videoId: "gTXgY5XbbZo",
    book: "예레미야",
    chapters: "38~41장",
    title: "예레미야 38~41장",
  },
  {
    day: 241,
    playlistIndex: 124,
    videoId: "pnMuJ-TG3Jk",
    book: "예레미야",
    chapters: "42~44장",
    title: "예레미야 42~44장",
  },
  {
    day: 242,
    playlistIndex: 123,
    videoId: "V5xqT7Liuhc",
    book: "예레미야",
    chapters: "45~48장",
    title: "예레미야 45~48장",
  },
  {
    day: 243,
    playlistIndex: 122,
    videoId: "TBhNxPlBM8w",
    book: "예레미야",
    chapters: "49~50장",
    title: "예레미야 49~50장",
  },
  {
    day: 244,
    playlistIndex: 121,
    videoId: "HzYU8lxgy30",
    book: "예레미야",
    chapters: "51~52장",
    title: "예레미야 51~52장",
  },
  {
    day: 245,
    playlistIndex: 120,
    videoId: "Jzzx67Mro7s",
    book: "예레미야애가",
    chapters: "1~2장",
    title: "예레미야애가 1~2장",
  },
  {
    day: 246,
    playlistIndex: 119,
    videoId: "2aIBdE9bjjc",
    book: "예레미야애가",
    chapters: "3~5장",
    title: "예레미야애가 3~5장",
  },
  {
    day: 247,
    playlistIndex: 118,
    videoId: "dnHZ_vtQIwE",
    book: "에스겔",
    chapters: "1~4장",
    title: "에스겔 1~4장",
  },
  {
    day: 248,
    playlistIndex: 117,
    videoId: "GuqSHByL2Z0",
    book: "에스겔",
    chapters: "5~8장",
    title: "에스겔 5~8장",
  },
  {
    day: 249,
    playlistIndex: 116,
    videoId: "Yb7tnDstG7M",
    book: "에스겔",
    chapters: "9~12장",
    title: "에스겔 9~12장",
  },
  {
    day: 250,
    playlistIndex: 115,
    videoId: "C4jdjQF_yUI",
    book: "에스겔",
    chapters: "13~15장",
    title: "에스겔 13~15장",
  },
  {
    day: 251,
    playlistIndex: 114,
    videoId: "9SYVCfJ7HG4",
    book: "에스겔",
    chapters: "16장",
    title: "에스겔 16장",
  },
  {
    day: 252,
    playlistIndex: 113,
    videoId: "TbsTLW88TUM",
    book: "에스겔",
    chapters: "17~19장",
    title: "에스겔 17~19장",
  },
  {
    day: 253,
    playlistIndex: 112,
    videoId: "gcmny3loAj4",
    book: "에스겔",
    chapters: "20~22장",
    title: "에스겔 20~22장",
  },
  {
    day: 254,
    playlistIndex: 111,
    videoId: "1NGoHHN4lbo",
    book: "에스겔",
    chapters: "23~24장",
    title: "에스겔 23~24장",
  },
  {
    day: 255,
    playlistIndex: 110,
    videoId: "Y-7eLGs8h5U",
    book: "에스겔",
    chapters: "25~27장",
    title: "에스겔 25~27장",
  },
  {
    day: 256,
    playlistIndex: 109,
    videoId: "Vz4V41_aS6s",
    book: "에스겔",
    chapters: "28~30장",
    title: "에스겔 28~30장",
  },
  {
    day: 257,
    playlistIndex: 108,
    videoId: "jFapv882pyc",
    book: "에스겔",
    chapters: "31~33장",
    title: "에스겔 31~33장",
  },
  {
    day: 258,
    playlistIndex: 107,
    videoId: "VWa0bvm2rF8",
    book: "에스겔",
    chapters: "34~36장",
    title: "에스겔 34~36장",
  },
  {
    day: 259,
    playlistIndex: 106,
    videoId: "wpovrgs_95I",
    book: "에스겔",
    chapters: "37~39장",
    title: "에스겔 37~39장",
  },
  {
    day: 260,
    playlistIndex: 105,
    videoId: "594nj4rDfg4",
    book: "에스겔",
    chapters: "40~41장",
    title: "에스겔 40~41장",
  },
  {
    day: 261,
    playlistIndex: 104,
    videoId: "uPCZw7Ss9wI",
    book: "에스겔",
    chapters: "42~44장",
    title: "에스겔 42~44장",
  },
  {
    day: 262,
    playlistIndex: 103,
    videoId: "0BFTvvB6j0o",
    book: "에스겔",
    chapters: "45~48장",
    title: "에스겔 45~48장",
  },
  {
    day: 263,
    playlistIndex: 102,
    videoId: "tUMw8eDkBFM",
    book: "다니엘",
    chapters: "1~2장",
    title: "다니엘 1~2장",
  },
  {
    day: 264,
    playlistIndex: 101,
    videoId: "AWaQgdOGZZE",
    book: "다니엘",
    chapters: "3~4장",
    title: "다니엘 3~4장",
  },
  {
    day: 265,
    playlistIndex: 100,
    videoId: "rcu7aAb4bbM",
    book: "다니엘",
    chapters: "5~6장",
    title: "다니엘 5~6장",
  },
  {
    day: 266,
    playlistIndex: 99,
    videoId: "0aw39L60MFQ",
    book: "다니엘",
    chapters: "7~9장",
    title: "다니엘 7~9장",
  },
  {
    day: 267,
    playlistIndex: 98,
    videoId: "ZGFqcQWbnSQ",
    book: "다니엘",
    chapters: "10~12장",
    title: "다니엘 10~12장",
  },
  {
    day: 268,
    playlistIndex: 97,
    videoId: "FFRAza4Qn_M",
    book: "호세아",
    chapters: "1~6장",
    title: "호세아 1~6장",
  },
  {
    day: 269,
    playlistIndex: 96,
    videoId: "ON2YXDyv9E0",
    book: "호세아",
    chapters: "7~9장",
    title: "호세아 7~9장",
  },
  {
    day: 270,
    playlistIndex: 95,
    videoId: "x1lfWtkvrfo",
    book: "호세아",
    chapters: "10~14장",
    title: "호세아 10~14장",
  },
  {
    day: 271,
    playlistIndex: 94,
    videoId: "u0lsp5vO74c",
    book: "요엘",
    chapters: "1~3장",
    title: "요엘 1~3장",
  },
  {
    day: 272,
    playlistIndex: 93,
    videoId: "3zAQi860Cf8",
    book: "아모스",
    chapters: "1~4장",
    title: "아모스 1~4장",
  },
  {
    day: 273,
    playlistIndex: 92,
    videoId: "7s17ehhupU0",
    book: "아모스",
    chapters: "5~9장",
    title: "아모스 5~9장",
  },
  {
    day: 274,
    playlistIndex: 91,
    videoId: "0zuMswIAEJ4",
    book: "오바댜",
    chapters: "1장, 요나 1~4장",
    title: "오바댜 1장, 요나 1~4장",
  },
  {
    day: 275,
    playlistIndex: 90,
    videoId: "SPIyfQP9FNo",
    book: "미가",
    chapters: "1~7장",
    title: "미가 1~7장",
  },
  {
    day: 276,
    playlistIndex: 89,
    videoId: "8uUNwi4N1YU",
    book: "나훔",
    chapters: "1~3장, 하박국 1~3장",
    title: "나훔 1~3장, 하박국 1~3장",
  },
  {
    day: 277,
    playlistIndex: 88,
    videoId: "M5qoF8z04_o",
    book: "스바냐",
    chapters: "1~3장, 학개 1~2장",
    title: "스바냐 1~3장, 학개 1~2장",
  },
  {
    day: 278,
    playlistIndex: 87,
    videoId: "mnFef3FTI_4",
    book: "스가랴",
    chapters: "1~6장",
    title: "스가랴 1~6장",
  },
  {
    day: 279,
    playlistIndex: 86,
    videoId: "w5EHR2yeofo",
    book: "스가랴",
    chapters: "7~10장",
    title: "스가랴 7~10장",
  },
  {
    day: 280,
    playlistIndex: 85,
    videoId: "ndS7otzKzyk",
    book: "스가랴",
    chapters: "11~14장",
    title: "스가랴 11~14장",
  },
  {
    day: 281,
    playlistIndex: 84,
    videoId: "Wp57S4ZFDS8",
    book: "말라기",
    chapters: "1~4장",
    title: "말라기 1~4장",
  },
  {
    day: 282,
    playlistIndex: 83,
    videoId: "nIDtkxY4eys",
    book: "마태복음",
    chapters: "1~4장",
    title: "마태복음 1~4장",
  },
  {
    day: 283,
    playlistIndex: 82,
    videoId: "BoBASboFdUI",
    book: "마태복음",
    chapters: "5~6장",
    title: "마태복음 5~6장",
  },
  {
    day: 284,
    playlistIndex: 81,
    videoId: "Eb56kBarKUU",
    book: "마태복음",
    chapters: "7~9장",
    title: "마태복음 7~9장",
  },
  {
    day: 285,
    playlistIndex: 80,
    videoId: "2feIOay7bv0",
    book: "마태복음",
    chapters: "10~12장",
    title: "마태복음 10~12장",
  },
  {
    day: 286,
    playlistIndex: 79,
    videoId: "e1e3CDIrAOQ",
    book: "마태복음",
    chapters: "13~14장",
    title: "마태복음 13~14장",
  },
  {
    day: 287,
    playlistIndex: 78,
    videoId: "hESoT6z4g5w",
    book: "마태복음",
    chapters: "15~17장",
    title: "마태복음 15~17장",
  },
  {
    day: 288,
    playlistIndex: 77,
    videoId: "b3eafH-YO-I",
    book: "마태복음",
    chapters: "18~20장",
    title: "마태복음 18~20장",
  },
  {
    day: 289,
    playlistIndex: 76,
    videoId: "99-BdQ4AFBo",
    book: "마태복음",
    chapters: "21~22장",
    title: "마태복음 21~22장",
  },
  {
    day: 290,
    playlistIndex: 75,
    videoId: "euWuR_DV5ZM",
    book: "마태복음",
    chapters: "23~24장",
    title: "마태복음 23~24장",
  },
  {
    day: 291,
    playlistIndex: 74,
    videoId: "jEYH4iMWzto",
    book: "마태복음",
    chapters: "25~26장",
    title: "마태복음 25~26장",
  },
  {
    day: 292,
    playlistIndex: 73,
    videoId: "5lzsm2LPwa8",
    book: "마태복음",
    chapters: "27~28장",
    title: "마태복음 27~28장",
  },
  {
    day: 293,
    playlistIndex: 72,
    videoId: "R8cvX08llxA",
    book: "마가복음",
    chapters: "1~3장",
    title: "마가복음 1~3장",
  },
  {
    day: 294,
    playlistIndex: 71,
    videoId: "lDBqv0Bpuy4",
    book: "마가복음",
    chapters: "4~5장",
    title: "마가복음 4~5장",
  },
  {
    day: 295,
    playlistIndex: 70,
    videoId: "lJuw-Jnm8UU",
    book: "마가복음",
    chapters: "6~7장",
    title: "마가복음 6~7장",
  },
  {
    day: 296,
    playlistIndex: 69,
    videoId: "7vNeg1yu6Bc",
    book: "마가복음",
    chapters: "8~9장",
    title: "마가복음 8~9장",
  },
  {
    day: 297,
    playlistIndex: 68,
    videoId: "65sOJ0t8QjU",
    book: "마가복음",
    chapters: "10~11장",
    title: "마가복음 10~11장",
  },
  {
    day: 298,
    playlistIndex: 67,
    videoId: "7CgVU9aWmYw",
    book: "마가복음",
    chapters: "12~13장",
    title: "마가복음 12~13장",
  },
  {
    day: 299,
    playlistIndex: 66,
    videoId: "RrPqQYVEyg4",
    book: "마가복음",
    chapters: "14~16장",
    title: "마가복음 14~16장",
  },
  {
    day: 300,
    playlistIndex: 65,
    videoId: "A4QQmaQrk0U",
    book: "누가복음",
    chapters: "1~2장",
    title: "누가복음 1~2장",
  },
  {
    day: 301,
    playlistIndex: 64,
    videoId: "FBGcgMc-4_k",
    book: "누가복음",
    chapters: "3~4장",
    title: "누가복음 3~4장",
  },
  {
    day: 302,
    playlistIndex: 63,
    videoId: "1_GGNZWqmIs",
    book: "누가복음",
    chapters: "5~6장",
    title: "누가복음 5~6장",
  },
  {
    day: 303,
    playlistIndex: 62,
    videoId: "kOmsjuOEJx0",
    book: "누가복음",
    chapters: "7~8장",
    title: "누가복음 7~8장",
  },
  {
    day: 304,
    playlistIndex: 61,
    videoId: "Zc2tdMjII9Y",
    book: "누가복음",
    chapters: "9~10장",
    title: "누가복음 9~10장",
  },
  {
    day: 305,
    playlistIndex: 60,
    videoId: "WnjD6LExLjc",
    book: "누가복음",
    chapters: "11~12장",
    title: "누가복음 11~12장",
  },
  {
    day: 306,
    playlistIndex: 59,
    videoId: "jAbSxdSgUw8",
    book: "누가복음",
    chapters: "13~15장",
    title: "누가복음 13~15장",
  },
  {
    day: 307,
    playlistIndex: 58,
    videoId: "n5S_lOEw1dw",
    book: "누가복음",
    chapters: "16~18장",
    title: "누가복음 16~18장",
  },
  {
    day: 308,
    playlistIndex: 57,
    videoId: "NPSYyR_EoZs",
    book: "누가복음",
    chapters: "19~20장",
    title: "누가복음 19~20장",
  },
  {
    day: 309,
    playlistIndex: 56,
    videoId: "HBzeSwddjZg",
    book: "누가복음",
    chapters: "21~22장",
    title: "누가복음 21~22장",
  },
  {
    day: 310,
    playlistIndex: 55,
    videoId: "WQeI4I-RWq8",
    book: "누가복음",
    chapters: "23~24장",
    title: "누가복음 23~24장",
  },
  {
    day: 311,
    playlistIndex: 54,
    videoId: "zGyBmv7MYAo",
    book: "요한복음",
    chapters: "1~3장",
    title: "요한복음 1~3장",
  },
  {
    day: 312,
    playlistIndex: 53,
    videoId: "ZoymTSAtGNM",
    book: "요한복음",
    chapters: "4~5장",
    title: "요한복음 4~5장",
  },
  {
    day: 313,
    playlistIndex: 52,
    videoId: "T170aqxnt6Y",
    book: "요한복음",
    chapters: "6~7장",
    title: "요한복음 6~7장",
  },
  {
    day: 314,
    playlistIndex: 51,
    videoId: "p0rDYxG2y6Q",
    book: "요한복음",
    chapters: "8~9장",
    title: "요한복음 8~9장",
  },
  {
    day: 315,
    playlistIndex: 50,
    videoId: "dCv0KQ3zPIM",
    book: "요한복음",
    chapters: "10~11장",
    title: "요한복음 10~11장",
  },
  {
    day: 316,
    playlistIndex: 49,
    videoId: "H1EdgqK09pU",
    book: "요한복음",
    chapters: "12~13장",
    title: "요한복음 12~13장",
  },
  {
    day: 317,
    playlistIndex: 48,
    videoId: "HydiL7s06fc",
    book: "요한복음",
    chapters: "14~16장",
    title: "요한복음 14~16장",
  },
  {
    day: 318,
    playlistIndex: 47,
    videoId: "LNcLMdFgKJo",
    book: "요한복음",
    chapters: "17~18장",
    title: "요한복음 17~18장",
  },
  {
    day: 319,
    playlistIndex: 46,
    videoId: "9zgEWQ7m-kE",
    book: "요한복음",
    chapters: "19~21장",
    title: "요한복음 19~21장",
  },
  {
    day: 320,
    playlistIndex: 45,
    videoId: "MLaB9ch43Lc",
    book: "사도행전",
    chapters: "1~3장",
    title: "사도행전 1~3장",
  },
  {
    day: 321,
    playlistIndex: 44,
    videoId: "wYMLDviGb-U",
    book: "사도행전",
    chapters: "4~6장",
    title: "사도행전 4~6장",
  },
  {
    day: 322,
    playlistIndex: 43,
    videoId: "ibXqvsEFy_8",
    book: "사도행전",
    chapters: "7~8장",
    title: "사도행전 7~8장",
  },
  {
    day: 323,
    playlistIndex: 42,
    videoId: "6cFuBGNjATI",
    book: "사도행전",
    chapters: "9~10장",
    title: "사도행전 9~10장",
  },
  {
    day: 324,
    playlistIndex: 41,
    videoId: "x2YuTtBWyAs",
    book: "사도행전",
    chapters: "11~13장",
    title: "사도행전 11~13장",
  },
  {
    day: 325,
    playlistIndex: 40,
    videoId: "-d3AV19c6Ow",
    book: "사도행전",
    chapters: "14~16장",
    title: "사도행전 14~16장",
  },
  {
    day: 326,
    playlistIndex: 39,
    videoId: "zg28UhyafCw",
    book: "사도행전",
    chapters: "17~19장",
    title: "사도행전 17~19장",
  },
  {
    day: 327,
    playlistIndex: 38,
    videoId: "uP-2MJWJjzs",
    book: "사도행전",
    chapters: "20~22장",
    title: "사도행전 20~22장",
  },
  {
    day: 328,
    playlistIndex: 37,
    videoId: "bYdQTvMSYB4",
    book: "사도행전",
    chapters: "23~25장",
    title: "사도행전 23~25장",
  },
  {
    day: 329,
    playlistIndex: 36,
    videoId: "V01Ef0wFRH4",
    book: "사도행전",
    chapters: "26~28장",
    title: "사도행전 26~28장",
  },
  {
    day: 330,
    playlistIndex: 35,
    videoId: "5h0ri9spLMc",
    book: "로마서",
    chapters: "1~4장",
    title: "로마서 1~4장",
  },
  {
    day: 331,
    playlistIndex: 34,
    videoId: "DUlZ-rkaQi0",
    book: "로마서",
    chapters: "5~8장",
    title: "로마서 5~8장",
  },
  {
    day: 332,
    playlistIndex: 33,
    videoId: "l0uxKUh270A",
    book: "로마서",
    chapters: "9~12장",
    title: "로마서 9~12장",
  },
  {
    day: 333,
    playlistIndex: 32,
    videoId: "_k_4o3TMlnY",
    book: "로마서",
    chapters: "13~16장",
    title: "로마서 13~16장",
  },
  {
    day: 334,
    playlistIndex: 31,
    videoId: "0Gxa_lq1HfY",
    book: "고린도전서",
    chapters: "1~5장",
    title: "고린도전서 1~5장",
  },
  {
    day: 335,
    playlistIndex: 30,
    videoId: "zIe1YPdLBHU",
    book: "고린도전서",
    chapters: "6~9장",
    title: "고린도전서 6~9장",
  },
  {
    day: 336,
    playlistIndex: 29,
    videoId: "DguA6lP9NyE",
    book: "고린도전서",
    chapters: "10~13장",
    title: "고린도전서 10~13장",
  },
  {
    day: 337,
    playlistIndex: 28,
    videoId: "TMFBJBHfg_Q",
    book: "고린도전서",
    chapters: "14~16장",
    title: "고린도전서 14~16장",
  },
  {
    day: 338,
    playlistIndex: 27,
    videoId: "nITvvvEJuZs",
    book: "고린도후서",
    chapters: "1~5장",
    title: "고린도후서 1~5장",
  },
  {
    day: 339,
    playlistIndex: 26,
    videoId: "nwj0h7JE0q8",
    book: "고린도후서",
    chapters: "6~10장",
    title: "고린도후서 6~10장",
  },
  {
    day: 340,
    playlistIndex: 25,
    videoId: "ikq7HG2O8DQ",
    book: "고린도후서",
    chapters: "11~13장",
    title: "고린도후서 11~13장",
  },
  {
    day: 341,
    playlistIndex: 24,
    videoId: "SdpIsMzDDxc",
    book: "갈라디아서",
    chapters: "1~3장",
    title: "갈라디아서 1~3장",
  },
  {
    day: 342,
    playlistIndex: 23,
    videoId: "-j0Y0p2QNGA",
    book: "갈라디아서",
    chapters: "4~6장",
    title: "갈라디아서 4~6장",
  },
  {
    day: 343,
    playlistIndex: 22,
    videoId: "5HKGfPUSuCI",
    book: "에베소서",
    chapters: "1~3장",
    title: "에베소서 1~3장",
  },
  {
    day: 344,
    playlistIndex: 21,
    videoId: "jDHHvKc9bd4",
    book: "에베소서",
    chapters: "4~6장",
    title: "에베소서 4~6장",
  },
  {
    day: 345,
    playlistIndex: 20,
    videoId: "qNiFsGNqCeM",
    book: "빌립보서",
    chapters: "1~4장",
    title: "빌립보서 1~4장",
  },
  {
    day: 346,
    playlistIndex: 19,
    videoId: "xFwBvgKCTYk",
    book: "골로새서",
    chapters: "1~4장",
    title: "골로새서 1~4장",
  },
  {
    day: 347,
    playlistIndex: 18,
    videoId: "kACclaS-eq0",
    book: "데살로니가전서",
    chapters: "1~5장",
    title: "데살로니가전서 1~5장",
  },
  {
    day: 348,
    playlistIndex: 17,
    videoId: "OZu1ywWMVDM",
    book: "데살로니가후서",
    chapters: "1~3장",
    title: "데살로니가후서 1~3장",
  },
  {
    day: 349,
    playlistIndex: 16,
    videoId: "BsUWQxvLM38",
    book: "디모데전서",
    chapters: "1~6장",
    title: "디모데전서 1~6장",
  },
  {
    day: 350,
    playlistIndex: 15,
    videoId: "oz4rTpjh_Dc",
    book: "디모데후서",
    chapters: "1~4장",
    title: "디모데후서 1~4장",
  },
  {
    day: 351,
    playlistIndex: 14,
    videoId: "_oC7TDmRpns",
    book: "디도서",
    chapters: "1~3장, 빌레몬서 1장",
    title: "디도서 1~3장, 빌레몬서 1장",
  },
  {
    day: 352,
    playlistIndex: 13,
    videoId: "MbShLibJQ1c",
    book: "히브리서",
    chapters: "1~6장",
    title: "히브리서 1~6장",
  },
  {
    day: 353,
    playlistIndex: 12,
    videoId: "yuZzJAQZzNw",
    book: "히브리서",
    chapters: "7~10장",
    title: "히브리서 7~10장",
  },
  {
    day: 354,
    playlistIndex: 11,
    videoId: "GDcU-H7mr40",
    book: "히브리서",
    chapters: "11~13장",
    title: "히브리서 11~13장",
  },
  {
    day: 355,
    playlistIndex: 10,
    videoId: "Yl6SL3lfPK0",
    book: "야고보서",
    chapters: "1~5장",
    title: "야고보서 1~5장",
  },
  {
    day: 356,
    playlistIndex: 9,
    videoId: "7ycAodbB8o4",
    book: "베드로전서",
    chapters: "1~5장",
    title: "베드로전서 1~5장",
  },
  {
    day: 357,
    playlistIndex: 8,
    videoId: "zjSsNzv15LY",
    book: "베드로후서",
    chapters: "1~3장",
    title: "베드로후서 1~3장",
  },
  {
    day: 358,
    playlistIndex: 7,
    videoId: "_TkAf43NlqU",
    book: "요한1서",
    chapters: "1~4장",
    title: "요한1서 1~4장",
  },
  {
    day: 359,
    playlistIndex: 6,
    videoId: "PVNxaWrRCk8",
    book: "요한1서",
    chapters: "5장, 요한2서 1장, 요한3서 1장, 유다서 1장",
    title: "요한1서 5장, 요한2서 1장, 요한3서 1장, 유다서 1장",
  },
  {
    day: 360,
    playlistIndex: 5,
    videoId: "xWFbG2cdq_Y",
    book: "요한계시록",
    chapters: "1~3장",
    title: "요한계시록 1~3장",
  },
  {
    day: 361,
    playlistIndex: 4,
    videoId: "YW5oMIySV40",
    book: "요한계시록",
    chapters: "4~8장",
    title: "요한계시록 4~8장",
  },
  {
    day: 362,
    playlistIndex: 3,
    videoId: "M7BQhpsjRB0",
    book: "요한계시록",
    chapters: "9~12장",
    title: "요한계시록 9~12장",
  },
  {
    day: 363,
    playlistIndex: 2,
    videoId: "Z-eX2_YuPbs",
    book: "요한계시록",
    chapters: "13~16장",
    title: "요한계시록 13~16장",
  },
  {
    day: 364,
    playlistIndex: 1,
    videoId: "t2hd7KlGxJA",
    book: "요한계시록",
    chapters: "17~19장",
    title: "요한계시록 17~19장",
  },
  {
    day: 365,
    playlistIndex: 0,
    videoId: "x3GxYZUU72U",
    book: "요한계시록",
    chapters: "20~22장",
    title: "요한계시록 20~22장",
  },
];

export function groupKoreanBibleVideosByBook(
  videos: KoreanBibleVideo[] = koreanBibleVideos,
): KoreanBibleBookGroup[] {
  const groups: KoreanBibleBookGroup[] = [];

  for (const video of videos) {
    const lastGroup = groups[groups.length - 1];

    if (lastGroup && lastGroup.book === video.book) {
      lastGroup.items.push(video);
      lastGroup.endDay = video.day;
      continue;
    }

    groups.push({
      book: video.book,
      startDay: video.day,
      endDay: video.day,
      items: [video],
    });
  }

  return groups;
}

export function findKoreanBibleIndexByBook(book: string) {
  return koreanBibleVideos.findIndex((video) => video.book === book);
}

export function findKoreanBibleIndexByVideoId(videoId: string) {
  return koreanBibleVideos.findIndex((video) => video.videoId === videoId);
}

export function findKoreanBibleIndexByDay(day: number) {
  return koreanBibleVideos.findIndex((video) => video.day === day);
}

export function getKoreanBibleCompletionPercent(completedDays: number[]) {
  if (koreanBibleVideos.length === 0) return 0;

  const validDays = new Set(koreanBibleVideos.map((video) => video.day));
  const completedKnownDays = new Set(
    completedDays.filter((day) => validDays.has(day)),
  ).size;

  return Math.round((completedKnownDays / koreanBibleVideos.length) * 100);
}

export const englishBibleVideos: EnglishBibleVideo[] = [
  { book: "Genesis", videoId: "QcMquFbcfA0", title: "The Book of Genesis - The Beginning of Everything" },
  { book: "Exodus", videoId: "NSmevXhc6IA", title: "The Book of Exodus - When the Sea Opened" },
  { book: "Leviticus", videoId: "f1pi6NxQM1M", title: "Leviticus - The Fire of God and the Call to Holiness" },
  { book: "Numbers", videoId: "K4Tb4bxW_wg", title: "Book of Numbers - Faith, Rebellion, and Miracles in the Desert" },
  { book: "Deuteronomy", videoId: "nCUF23VOfQk", title: "The Book of Deuteronomy - The Final Words of Moses" },
  { book: "Joshua", videoId: "F7UImkCk9dg", title: "The Book of Joshua - The Walls Fell and Faith Rose" },
  { book: "Judges", videoId: "zBrj5-frffY", title: "Judges - Strength, Betrayal, and Redemption" },
  { book: "Ruth", videoId: "XbWetk7T0IY", title: "Ruth - From Loss to Love: A Story of Redemption" },
  { book: "2 Samuel", videoId: "iv2GMGlE4uQ", title: "2 Samuel - The Rise, the Fall, and the Heart of a King" },
  { book: "1 Chronicles", videoId: "Nzz3xAtxu5Y", title: "1 Chronicles - The Ark Returns. The Kingdom Rises." },
  { book: "2 Chronicles", videoId: "V8Som7IqrjY", title: "2 Chronicles - Full Book Study Edition" },
  { book: "Psalms", videoId: "0NHQ-udjHBA", title: "Psalms - Contemporary English Dramatized Audio" },
  { book: "Proverbs", videoId: "zBPSUjphjSY", title: "Proverbs 1 to 31 - Contemporary English With Text" },
  { book: "Ecclesiastes", videoId: "kNU9iP29STs", title: "Ecclesiastes - Everything Is Vanity" },
  { book: "Daniel", videoId: "QKu8Und6ZOg", title: "Daniel - Faith Among Lions" },
  { book: "Matthew", videoId: "mgUWg3ZY_C8", title: "The Gospel of Matthew - The Teachings of Christ" },
  { book: "Mark", videoId: "pP_RkiS8GsA", title: "The Gospel of Mark - Power, Miracles & Authority" },
  { book: "Luke", videoId: "PEMFlleaJnc", title: "The Gospel of Luke - From the Manger to the Cross" },
  { book: "John", videoId: "l1kQIiy-DZU", title: "The Gospel of John - Jesus The Light of the World" },
  { book: "Acts", videoId: "vRNs2Gkp-o8", title: "Acts of The Apostles - The Power of the Holy Spirit" },
  { book: "Romans", videoId: "khQ1J6mi334", title: "Romans - Nothing Can Separate Us" },
  { book: "1 Corinthians", videoId: "6l3_C_amcWc", title: "1 Corinthians - Faith, Gifts, and the Way of Love" },
  { book: "2 Corinthians", videoId: "X1SkUF0bo7g", title: "2 Corinthians - Treasure in Jars of Clay" },
  { book: "Galatians", videoId: "OSRov7Q9xC8", title: "Galatians - The Fruit of the Spirit" },
  { book: "Ephesians", videoId: "5uPnrFObVVw", title: "Ephesians - The Full Armor of God" },
  { book: "Philippians", videoId: "ZVeueRuxE6Y", title: "Philippians - Peace That Surpasses All Understanding" },
  { book: "Colossians", videoId: "lQiPwgvg2Wo", title: "Colossians - Christ Above All" },
  { book: "James", videoId: "vGlLthMA2Jw", title: "James - Faith Without Works Is Dead" },
  { book: "Revelation", videoId: "bF3JPv_-luI", title: "Revelation - The Last Vision of John" },
];
